### ISSUE TITLE
Session Flash Not Working in View. 

### ISSUE THREAD

**Issue by arif98741** [arif98741/codeigniter_crud#1]
I have set session by using **$this->session->set_flashdata()** but I can can't print the value in view . You someone solve the error please

![4](https://user-images.githubusercontent.com/17213478/45091480-683c5400-b134-11e8-99fd-9dd8aba11012.PNG)
![3](https://user-images.githubusercontent.com/17213478/45091481-683c5400-b134-11e8-9988-9dee53754434.PNG)
![2](https://user-images.githubusercontent.com/17213478/45091483-68d4ea80-b134-11e8-9a69-0e4121ab9fbe.PNG)
![1](https://user-images.githubusercontent.com/17213478/45091484-68d4ea80-b134-11e8-8793-feb749bbefbb.PNG)

**Comment by arif98741** [comment]
![1](https://user-images.githubusercontent.com/17213478/45091430-43e07780-b134-11e8-99f4-b3a88a99e17d.PNG)
![4](https://user-images.githubusercontent.com/17213478/45091431-43e07780-b134-11e8-902e-c5e17beb4313.PNG)
![3](https://user-images.githubusercontent.com/17213478/45091432-44790e00-b134-11e8-9356-e2d64c8cd3f3.PNG)
![2](https://user-images.githubusercontent.com/17213478/45091433-44790e00-b134-11e8-87c1-1b26b5e6cb9e.PNG)

**Comment by cyruzin** [comment]
Check my pull request.

**Comment by arif98741** [comment]
Thanks, dear. For your valuable contribution. I am checking.

**Comment by arif98741** [comment]
Thanks @cyruzin a lot
